# Generated by Django 6.0.6 on 2026-07-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_products_image_alter_products_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
